[package]
name = "aegis-portal-secret"
description = "Encrypted native Secret portal implementation for Aegis"
readme = "README.md"
publish = false
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
aegis-portal-runtime.workspace = true
async-channel = { workspace = true }
argon2 = { workspace = true }
chacha20poly1305 = { workspace = true }
dirs.workspace = true
hkdf = { workspace = true }
libc.workspace = true
log.workspace = true
rand = { workspace = true }
serde.workspace = true
serde_json.workspace = true
sha2 = { workspace = true }
thiserror.workspace = true
zbus.workspace = true
zeroize = { workspace = true, features = ["derive"] }
